"""Programmatic builder for the 7 .docx Jinja2 templates.

Real binary .docx templates cannot live comfortably in git, so they are built
on demand from the declarative DOC_SPECS using python-docx. The generated
files contain raw Jinja2 placeholders (e.g. ``{{ fir_number }}``) and docxtpl
row-loop tags (``{%tr for item in seized_items %}`` / ``{%tr endfor %}``)
that docxtpl later renders with real case data.

Run manually with:  python -m app.templates.build_templates [--force]
"""
from __future__ import annotations

import argparse
from pathlib import Path

from docx import Document as DocxDocument
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt

from app.templates.doc_specs import DOC_SPECS

TEMPLATE_DIR = Path(__file__).parent


def template_path(doc_type: str) -> Path:
    """Return the on-disk .docx path for a given document type."""
    return TEMPLATE_DIR / f"{doc_type.lower()}.docx"


def _add_centered(doc, text: str, size: int = 11, bold: bool = False) -> None:
    """Add a centered paragraph with the given font size / weight."""
    para = doc.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = para.add_run(text)
    run.bold = bold
    run.font.size = Pt(size)


def _add_meta_table(doc, meta_rows: list[tuple[str, str]]) -> None:
    """Add the 2-column label/value metadata table with raw placeholders."""
    table = doc.add_table(rows=len(meta_rows), cols=2)
    table.style = "Table Grid"
    for i, (label, placeholder) in enumerate(meta_rows):
        label_cell = table.rows[i].cells[0]
        label_cell.text = label
        for para in label_cell.paragraphs:
            for run in para.runs:
                run.bold = True
        table.rows[i].cells[1].text = placeholder


def _add_loop_table(doc, spec_table: dict) -> None:
    """Add a data table using docxtpl ``{%tr %}`` row-loop syntax.

    Layout (exactly what docxtpl expects):
        row 0: column headers
        row 1: ``{%tr for <var> in <source> %}`` in the FIRST cell (loop row)
        row 2: one data row with ``{{ <var>.<field> }}`` placeholders per cell
        row 3: ``{%tr endfor %}`` in the FIRST cell of a following row
    """
    columns = spec_table["columns"]
    caption = doc.add_paragraph()
    caption.add_run(spec_table["caption"]).bold = True

    table = doc.add_table(rows=4, cols=len(columns))
    table.style = "Table Grid"

    for col_idx, (header, _cell) in enumerate(columns):
        cell = table.rows[0].cells[col_idx]
        cell.text = header
        for para in cell.paragraphs:
            for run in para.runs:
                run.bold = True

    table.rows[1].cells[0].text = (
        f"{{%tr for {spec_table['loop_var']} in {spec_table['loop_source']} %}}"
    )
    for col_idx, (_header, cell_placeholder) in enumerate(columns):
        table.rows[2].cells[col_idx].text = cell_placeholder
    table.rows[3].cells[0].text = "{%tr endfor %}"


def _add_signatures(doc, sign_left: str, sign_right: str) -> None:
    """Add a 2-column borderless signature block table."""
    doc.add_paragraph()
    doc.add_paragraph()
    table = doc.add_table(rows=1, cols=2)  # default style: no visible borders
    for cell, sign_text in zip(table.rows[0].cells, (sign_left, sign_right)):
        first = True
        for line in ["____________________", *sign_text.split("\n")]:
            para = cell.paragraphs[0] if first else cell.add_paragraph()
            first = False
            para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            para.add_run(line)


def _build_one(doc_type: str, spec: dict, path: Path) -> None:
    """Build a single .docx template from its spec and save it to `path`."""
    doc = DocxDocument()

    for line in spec.get("header", []):
        _add_centered(doc, line, size=12, bold=True)
    _add_centered(doc, spec["title"], size=14, bold=True)
    _add_centered(doc, spec["subtitle"], size=10)
    _add_centered(doc, "_" * 72)

    _add_meta_table(doc, spec["meta_rows"])
    doc.add_paragraph()

    for text in spec["body_paragraphs"]:
        para = doc.add_paragraph(text)
        para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

    if spec.get("table"):
        _add_loop_table(doc, spec["table"])

    _add_signatures(doc, spec["sign_left"], spec["sign_right"])

    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run("Generated by CrimeGPT on {{ today }}")
    run.font.size = Pt(8)

    doc.save(str(path))


def build_all(force: bool = False) -> list[str]:
    """Build every missing .docx template; rebuild all when `force` is True.

    Returns the list of template file paths that were (re)built.
    """
    TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)
    built: list[str] = []
    for doc_type, spec in DOC_SPECS.items():
        path = template_path(doc_type)
        if path.exists() and not force:
            continue
        _build_one(doc_type, spec, path)
        built.append(str(path))
    return built


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build the CrimeGPT .docx templates.")
    parser.add_argument("--force", action="store_true", help="rebuild even if files exist")
    args = parser.parse_args()
    built_files = build_all(force=args.force)
    if built_files:
        for f in built_files:
            print(f"built {f}")
    else:
        print("all templates already exist (use --force to rebuild)")
